8.0 ekstensions 2
open-synergy/opnsynid-account-invoicing pull request #28
Opened 2019-10-24 13:09 UTC by mikevhe18

2019-10-26 05:05 UTC, andhit-r requested changes
@mikevhe18 ada revisi yah

2019-10-26 05:05 UTC, andhit-r commented on account_debt_collection/models/account_invoice.py
> +    debt_collection_detail_id = fields.Many2one(
Mike ini ngisinya dimana?

2019-10-26 05:05 UTC, andhit-r commented on account_debt_collection/security/ir.model.access.csv
> +account_debt_collection_detail_summary_employee,account.debt_collection_detail_summary - user,model_account_debt_collection_detail_summary,base.group_user,1,1,1,1
Ini tdk perlu krn obj tdk bisa dicreate edit delete

2019-10-26 05:05 UTC, andhit-r commented on account_debt_collection/views/account_debt_collection_views.xml
> +                      <separator string="By Partner(s)" colspan="4"/>
Ini dipisah aja di tab berbeda. Stringnya "Summary by Partner"

2019-10-26 06:24 UTC, mikevhe18 commented on account_debt_collection/models/account_invoice.py
> +    debt_collection_detail_id = fields.Many2one(
@andhit-r Ngisinya di wizard pas import mas

2019-10-26 06:26 UTC, mikevhe18 commented on account_debt_collection/views/account_debt_collection_views.xml
> +                      <separator string="By Partner(s)" colspan="4"/>
@andhit-r Awalnya gw pisah di tab baru mas, tapi jadinya kepanjangan kesamping, terlalu banyak tab, akhirnya gw jadinya disatuin. Di satu sisi gw mikirnya akan lebih mudah buat user ngebandingin antara invoicenya karena ga usah pindah2 tab

2019-10-28 07:51 UTC, andhit-r commented on account_debt_collection/views/account_debt_collection_views.xml
> +                      <separator string="By Partner(s)" colspan="4"/>
Ok

2019-10-28 07:53 UTC, andhit-r commented on account_debt_collection/models/account_invoice.py
> +    debt_collection_detail_id = fields.Many2one(
Maksud gw kode tambahan di wizardnya udah lo tambahin? Atau udah yakin dah ke commit? Karena di PR ini ga ada perubahan kode di wizardnya. Sedangkan fieldnya baru lo tambahin di PR ini.

2019-10-30 00:57 UTC, merged