[account_invoice_sequence_configurator] 8.0.1.0.0
open-synergy/opnsynid-account-invoicing pull request #49
Opened 2021-06-28 02:05 UTC by mikevhe18

2021-06-29 07:09 UTC, andhit-r requested changes

2021-06-29 07:09 UTC, andhit-r commented on account_invoice_sequence_configurator/models/account_invoice.py
> +        sequence = self._create_sequence()
Baris 32 S.D. 61 bisa dihilangkan jika lo jalananin
   
_super = super(AccountInvoice, self)
sequence = self._create_sequence()
self.write({"internal_number":sequence})
res = _super.action_number()

Jangan lupa ditest dulu

2021-06-29 07:09 UTC, andhit-r commented on account_invoice_sequence_configurator/data/base_sequence_configurator_data.xml
> +            >result = document.journal_id.invoice_sequence_id</field>
Ini kenapa butuh sequence tambahan? Kenapa tidak gunakan field sequence_id yg sudah ada

2021-07-01 04:30 UTC, mikevhe18 commented on account_invoice_sequence_configurator/models/account_invoice.py
> +        sequence = self._create_sequence()
Ga bisa mas, kalau kita returnnya res lagi tanpa di if.
Fungsi yang lama akan dijalankan lagi sehingga numbernya akan balik lagi diupdate ke fungsi yg lama.
Makanya gw pake if, dan returnnya True kalau ada sequence.
Jadi untuk baris 32 s/d 61 harus ditulis ulang

2021-07-01 04:32 UTC, mikevhe18 commented on account_invoice_sequence_configurator/data/base_sequence_configurator_data.xml
> +            >result = document.journal_id.invoice_sequence_id</field>
Karena field sequence_id di journal itu yg pakai banyak mas, bakal merubah settingan yg sudah berjalan ga kira2 ?
Kalau dibuatkan 1 field sequence khusus untuk invoice, jadinya untuk sequence yg lain tidak akan pengaruh

2021-07-01 08:00 UTC, andhit-r requested changes

2021-07-01 08:00 UTC, andhit-r commented on account_invoice_sequence_configurator/data/base_sequence_configurator_data.xml
> +            >result = document.journal_id.invoice_sequence_id</field>
Justru klo dibuat field baru akan merubah setingan di banyak tempat mike.

2021-07-01 08:00 UTC, andhit-r commented on account_invoice_sequence_configurator/models/account_invoice.py
> +        sequence = self._create_sequence()
Ini gw lagi coba

2021-07-01 08:11 UTC, andhit-r commented on account_invoice_sequence_configurator/models/account_invoice.py
> +        sequence = self._create_sequence()
ok

2021-07-02 04:48 UTC, andhit-r requested changes

2021-07-02 04:48 UTC, andhit-r commented on account_invoice_sequence_configurator/data/base_sequence_configurator_data.xml
> +                search="[('model_id.model','=','account.invoice'),('name','=','name')]"
Ini lgs ke field internal_number saja, field name penggunaannya berbeda pada invoice

2021-07-02 04:48 UTC, andhit-r commented on account_invoice_sequence_configurator/models/account_invoice.py
> +    )
Ini tidak perlu mike. Gunakan field internal_number

2021-07-02 04:48 UTC, andhit-r commented on account_invoice_sequence_configurator/models/account_invoice.py
> +            sequence = document._create_sequence()
_create_sequence nya jalankan dengan mempertimbangkan implementasi sequence_range. Gunakan field date_invoice.

2021-07-02 13:45 UTC, merged